spring.application.name=order-service
server.port=8085

# ===========================================================
# MongoDB Configuration
# ===========================================================
# تأكد من كتابة الباسورد الحقيقي مكان كلمة Password وبدون مسافات
spring.data.mongodb.uri=mongodb+srv://Adelrhman_db:Password@cluster0.b2ezvqb.mongodb.net/order_db?retryWrites=true&w=majority&appName=Order_db
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# ===========================================================
# Eureka Discovery Configuration
# ===========================================================
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ===========================================================
# Kafka Common Configuration
# ===========================================================
spring.kafka.bootstrap-servers=kafka:29092

# ===========================================================
# Kafka Producer Configuration
# ===========================================================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ===========================================================
# Kafka Consumer Configuration
# ===========================================================
spring.kafka.consumer.group-id=order-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# استخدام ErrorHandlingDeserializer بشكل صحيح لمنع الـ Serialization Errors
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# إعدادات الـ JSON
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.Map
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ===========================================================
# Error Handling Configuration
# ===========================================================
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
server.error.include-exception=false